[package]
name = "api"
version = "0.9.0"
authors = ["Marc Schreiber <marc.schreiber@aixigo.de>"]
repository = "https://github.com/aixigo/PREvant/"

[dependencies]
crossbeam = "0.4"
crossbeam-utils = "0.5"
dkregistry = "0.2"
goji = "0.2"
hyper = "0.10"
log = "0.4"
multimap = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.7"
shiplift = { git = "https://github.com/schrieveslaach/shiplift", rev = "4669fb03575c1c511411f055cd8823c1ffb26da0" }
tokio = "0.1"
tokio-core = "0.1"
toml = "0.4"
regex = "1.0"
rocket = "0.4.0-rc.2"
rocket_codegen = "0.4.0-rc.2"
rocket_contrib = "0.4.0-rc.2"
url = "1.7"

